services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hour1819
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "1111:5432"
    volumes:
      - D:/pgdata:/var/lib/postgresql/data
      - D:/pg_backup:/backup
    command: >
      postgres 
      -c listen_addresses='*' 
      -c password_encryption=scram-sha-256
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - postgres_network

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin123
#    ports:
#      - "5050:80"
#    volumes:
#      - D:/pgadmin_data:/var/lib/pgadmin
#      - D:/pg_backup:/backup
#    networks:
#      - postgres_network

networks:
  postgres_network:
    driver: bridge